### ISSUE TITLE
Printing in MJF nylon

### ISSUE THREAD

**Issue by heyitscassio** [pseudoku/PseudoKeyCapProfiles#2]
Hello, first of all that's a really nice project.

Since jlcpcb started receiving 3d printing orders, I wanted to get a set of keycaps printed by them in MJF nylon. Anyone has tried that with success? Or will I be the guinea pig?

**Comment by deanraspa** [comment]
@toniz4, did you end up getting them printed?  I am in the same boat.

**Comment by caksoylar** [comment]
I got the DES keycaps printed in MJF with JLCPCB. They asked a few questions about weak spots and I accepted the risk. The keycaps turned out fine: The stem holes for about half of the keycaps were a bit loose so it wobbles on my switches, but I worked around it by putting some scotch tape on the stems before inserting the keycaps and it tightened things up enough.

**Comment by heyitscassio** [comment]
@caksoylar Did you changed the Tol parameter? By default it adds some tolerance to the stem holes, did you had setted to 0?

**Comment by caksoylar** [comment]
@toniz4 I used the default settings in the thumb and convex scads, but used the STLs Pseudoku posted themselves at their Discord channel. I haven't compared those STLs to those generated from the scad file directly to say whether they are different or not.

Here is a direct link to the STLs on the Discord channel: https://discord.com/channels/714176584269168732/879817722328920174/953708184848179240
Here is an invite to the server if you need it: https://discord.gg/DbCfZfZ

**Comment by heyitscassio** [comment]
I 3d printed those in mjf, in general it fits really thigh with `Tol = 0`. Here are the details:

https://www.reddit.com/r/ErgoMechKeyboards/comments/waj7zw/mjf_3d_printed_pseudoku_keycaps/
